development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: complitech_task
  pool: 5
  username: root
  password: root

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: complitech_test
  pool: 5
  username: root
  password: root

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: complitech_task
  pool: 5
  username: root
  password: root